# basic options
title: Blog
author: daynat
email: fangyutan@foxmail.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
